def diasemana(dia:str):
    match (dia):
        case 'domingo':
            return 1
        case 'segunda':
            return 2
        case 'terca':
            return 3
        case 'quarta':
            return 4
        case 'quinta':
            return 5
        case 'sexta':
            return 6
        case 'sabado':
            return 7
